ol:
  config:
    apiPackage: com.tux_api.openlegacy
    apiSourceFolder: src/main/java
    backendSolution: orchestration
    designtimeContext: default
    frontendSolution: orchestration-rest
    referredProjects:
    - tux-sdk
    sourceFetcher: sourceFetcher
    webPackage: com.tux_api.openlegacy.web
