ol:
  config:
    apiPackage: com.mysql_table_api.openlegacy
    apiSourceFolder: src/main/java
    backendSolution: orchestration
    designtimeContext: default
    frontendSolution: orchestration-rest
    generateImpl: true
    referredProjects:
    - mysql-table-sdk
    sourceFetcher: sourceFetcher
    webPackage: com.mysql_table_api.openlegacy.web
