ol:
  # Openlegacy Common Properties (OLCommonProperties) #
  common:
    right-to-left: false
    project:
      oracleCustomerSdk:
        backend-solution: JDBC
        live-session: true
        trail-path: /trails/oracle-customer-sdk.trail
        cache:
          enabled: true
  database:
    project:
      oracleCustomerSdk:
        url: jdbc:oracle:thin:@//localhost:1521/xe
        driverClassName: oracle.jdbc.driver.OracleDriver
        username: system
        password: '{cipher}dfe302bb99828c02f371034b26210a12b976916a2050376f36f734ae2fe4f2d1'

