ol:
  # Openlegacy Common Properties (OLCommonProperties) #
  common:
    right-to-left: false
    project:
      mssqlSpSdk:
        backend-solution: STORED_PROCEDURES
        live-session: true
        trail-path: /trails/mssql-sp-sdk.trail
        cache:
          enabled: true
  database:
    project:
      mssqlSpSdk:
        url: jdbc:sqlserver://localhost:1433;databaseName=openlegacy
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
        username: sa
        password: '{cipher}7181ff2aa15ce60e50c028a9a7a41f48682e9d01f0f12f9b4c608ff478525df7'

