# Logging #
#logging:
#  level:
#    org:
#      openlegacy: debug

# Security #
security:
  # Spring security OAuth2 configuration #
  oauth2:
    resource:
      filter-order: 3

# Springfox #
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/swagger.json

# Openlegacy #
ol:
  # Openlegacy Common Properties (OLCommonProperties) #
  common:
    user-properties-folder-name: tux-api
    cache:
      enabled: true

---

# tuxSdk
ol:
  # Openlegacy Common Properties (OLCommonProperties) #
  common:
    right-to-left: false
    project:
      tuxSdk:
        backend-solution: TUXEDO
        live-session: true
        trail-path: /trails/tux-sdk.trail
        cache:
          enabled: true
  tuxedo:
    project:
      tuxSdk:
        app-address: //tuxedo.openlegacy.org:8001
        validate-fields-as-list: true




