ol:
  # Openlegacy Common Properties (OLCommonProperties) #
  common:
    right-to-left: false
    project:
      wsdlSdk:
        backend-solution: WEB_SERVICES
        live-session: true
        trail-path: /trails/wsdl-sdk.trail
        cache:
          enabled: true
  url:
    project:
      wsdlSdk:
        baseUrl: http://www.thomas-bayer.com
        username: 
        password: 

