package com.tux_api.openlegacy.services;

import javax.inject.Inject;

import org.openlegacy.core.annotations.OpenlegacyDesigntime;
import org.openlegacy.core.annotations.services.BindFrom;
import org.openlegacy.core.annotations.services.BindInputs;
import org.openlegacy.core.annotations.services.BindOutputs;
import org.openlegacy.core.annotations.services.BindTo;
import org.openlegacy.core.annotations.services.EntityMapping;
import org.openlegacy.core.annotations.services.LogServiceUsage;
import org.openlegacy.core.annotations.services.Service;
import org.openlegacy.core.annotations.services.ServiceMethod;
import org.openlegacy.core.rpc.RpcSession;
import org.openlegacy.impl.services.ws.ServiceBinder;
import org.openlegacy.utils.ActionUtil;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

import com.tux_sdk.openlegacy.entities.Getuserdetails;

/**
 *  A service implementation which invokes OpenLegacy API, and returns a service output.
 *  The code below should be customize to perform a working scenario which goes through the relevant screens.
 *  Can be tested by invoking the test CustomerServiceServiceTest.
 *  The interface CustomerServiceService can be customized to enabling passing parameters to the service, and this class can consume the parameters within the relevant screens.
 */
@Service(name = "CustomerService")
@OpenlegacyDesigntime(editor = "WebServiceEditor")
@Component
public class CustomerServiceServiceImpl implements CustomerServiceService {

    @Inject
    private ApplicationContext applicationContext;


    @Inject
    private ServiceBinder serviceBinder;

    @Override
    @ServiceMethod(name = "getCustomerService", entities = {
            @EntityMapping(alias="getuserdetails", entity=com.tux_sdk.openlegacy.entities.Getuserdetails.class)})
    @LogServiceUsage
    @BindInputs(endpoints = {
            @BindTo(endpoint = "getuserdetails.id3", expression = "id3")})
    @BindOutputs(endpoints = {
            @BindFrom(endpoint = "getuserdetails", expression = "getuserdetails")})
    public CustomerServiceOut getCustomerService(CustomerServiceIn customerServiceIn) throws Exception {
        CustomerServiceOut customerServiceOut = new CustomerServiceOut();
        /* autogenerated - sessions block start*/
        ;
        RpcSession tuxSdkRpcSession = applicationContext.getBean("tuxSdkRpcSession", RpcSession.class);
        /* autogenerated - sessions block end */
        ;

        try {
            /* autogenerated - execution block start */;
            Getuserdetails getuserdetails = serviceBinder.bindInputs(this, "getCustomerService", "getuserdetails", new Getuserdetails(), customerServiceIn);
            getuserdetails = tuxSdkRpcSession.doAction(ActionUtil.getRpcAction(Getuserdetails.class), getuserdetails);
            /* autogenerated - execution block end */;

            /* autogenerated - output block start */;
            customerServiceOut = serviceBinder.bindOutput(this, "getCustomerService", customerServiceOut, new String[]{"customerServiceIn", "getuserdetails"}, customerServiceIn, getuserdetails);
            /* autogenerated - output block end */;

            return customerServiceOut;
        } finally {
            /* autogenerated - disconnect block start */
            ;
            tuxSdkRpcSession.disconnect();
            /* autogenerated - disconnect block end */
            ;
        }
    }

}
