ol:
  config:
    apiPackage: com.oracle_table_sdk.openlegacy
    apiSourceFolder: src/main/java
    backendSolution: jdbc
    dbDialect: org.hibernate.dialect.OracleDialect
    designtimeContext: default
    frontendSolution: java
    provider: ''
    repositoryPackage: com.oracle_table_sdk.openlegacy.repositories
    sourceFetcher: jdbcSourceFetcher
    webPackage: com.oracle_table_sdk.openlegacy.web
